### PR TITLE
Features: Create forms to insert data

### PR DESCRIPTION
**Pull request by redmarverick**
### [Project Requirements Achieved:](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/forms_project_v1_1.md)

- Created a method called current_user in your ApplicationController to make current user data available to all controllers.
- Created forms to perform the following functions:
1. Create a Post on behalf of the current_user
2. Create a comment on behalf of the current_user
3. Allow Users to add likes to Posts.

### CODE REVIEW

**Comment by jerryowusu** [comment]
Hello  @redmarverick kindly ensure  that your pull request has a descriptive title. Instead of saying  new functionality added, can you be more  explicit and detailed? What new functionality are you adding?

**Comment by redmarverick** [comment]
Request done @jerryowusu

**Comment by jerryowusu** [comment]
> Request done @jerryowusu

Screenshot from 2023-08-26 08-20-00

this is still not updated
You can check [this video](https://youtu.be/cnIDkME-gg0) on how to edit the PR title

**Comment by redmarverick** [comment]
I thought you meant the description, now I've changed the title too.
@jerryowusu

**Review by jerryowusu — APPROVED** [review]
Hi @redmarverick , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


weldone

## Highlights
Well organized and clean code :+1: 
ApplicationController contains `#current_user` method :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
